{"name": "test_invalid_credentials", "status": "passed", "steps": [{"name": "Открытие домашней страницы", "status": "passed", "start": 1750601723612, "stop": 1750601724691}, {"name": "Заполнение неверных данных пользователя", "status": "passed", "start": 1750601724861, "stop": 1750601724861}, {"name": "Проверка сообщения об ошибке", "status": "passed", "start": 1750601726260, "stop": 1750601726774}], "start": 1750601723612, "stop": 1750601726775, "uuid": "36886bb0-987a-49ef-a0bc-3aa3c7b721e9", "historyId": "ef7373e7d568430ffce9b3d52770a421", "testCaseId": "ef7373e7d568430ffce9b3d52770a421", "fullName": "tests.test_login.TestLogin#test_invalid_credentials", "labels": [{"name": "story", "value": "Неуспешная авторизация с неверными данными"}, {"name": "feature", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CASI0Q3"}, {"name": "thread", "value": "10316-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}